apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod2-replicaset
  labels:
    name: app2
spec:
  replicas: 0
  selector:
    matchLabels:
      name: app2
  template:
    metadata:
      name: pod2
      labels:
        name: app2
    spec:
      containers:
      - name: echo2
        image: registry.cluster.wik.cloud/public/echo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"